# Generated by Django 2.2b1 on 2019-03-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleemp',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='sampleemp',
            name='id',
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='PRODUCT_CODE',
            field=models.CharField(default=15, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
