# Generated by Django 2.2b1 on 2019-03-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190303_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleemp',
            name='BSID_SIZE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='LOADING_TYPE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='PATTERN',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='TYPE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='UNIT_VOL_cc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='UNIT_WT_Kg',
            field=models.FloatField(null=True),
        ),
    ]
