# Generated by Django 2.2b1 on 2019-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190303_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleemp',
            old_name='BSID_SIZE',
            new_name='TYRE_CODE',
        ),
        migrations.RemoveField(
            model_name='sampleemp',
            name='PATTERN',
        ),
        migrations.RemoveField(
            model_name='sampleemp',
            name='TYPE',
        ),
        migrations.RemoveField(
            model_name='sampleemp',
            name='UNIT_VOL_cc',
        ),
        migrations.RemoveField(
            model_name='sampleemp',
            name='UNIT_WT_Kg',
        ),
        migrations.RemoveField(
            model_name='sampleemp',
            name='empname',
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='VOLUME',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sampleemp',
            name='WEIGHT',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
